apiVersion: v1
kind: Service
metadata:
  name: site2-service
spec:
  selector:
    app: site2
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site2
spec:
  selector:
    matchLabels:
      app: site2
  replicas: 2
  template:
    metadata:
      labels:
        app: site2
    spec:
      containers:
      - name: site2
        image: nakib0296/html-docker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80